<?php

namespace config;

class file {

    public $saveFilePath = "/home/system/opt/data/order/again/";
    public $redis = array('host' => '192.168.1.234', 'port' => 6371);
    public $save_account_domain_field_ary = array(
        'domain',
        "view",
        "click",
        "reach",
        "action",
        "userClick",
        "userReach",
        "realSpend",
        "spend",
        "advSpend",
        "cSpend",
        "reportSpend",
        "kcSpend",
        "userAction",
        "action1",
        "userAction1",
        "action2",
        "userAction2",
        "action3",
        "userAction3",
        "action4",
        "userAction4",
        "action5",
        "userAction5",
    );
    public $save_account_place_field_ary = array(
        'behePlace',
        'place',
        'domain',
        "view",
        "click",
        "reach",
        "action",
        "userClick",
        "userReach",
        "realSpend",
        "spend",
        "advSpend",
        "cSpend",
        "reportSpend",
        "kcSpend",
        "userAction",
        "action1",
        "userAction1",
        "action2",
        "userAction2",
        "action3",
        "userAction3",
        "action4",
        "userAction4",
        "action5",
        "userAction5",
    );
    public $save_domain_field_ary = array(
        'domain',
        "view",
        "click",
        "reach",
        "action",
        "userClick",
        "userReach",
        "realSpend",
        "spend",
        "advSpend",
        "target",
        "firstTarget",
        "time",
        "cSpend",
        "reportSpend",
        "kcSpend",
        "userAction",
        "action1",
        "userAction1",
        "action2",
        "userAction2",
        "action3",
        "userAction3",
        "action4",
        "userAction4",
        "action5",
        "userAction5",
    );
    public $save_place_field_ary = array(
        'behePlace',
        'place',
        'domain',
        "view",
        "click",
        "reach",
        "action",
        "userClick",
        "userReach",
        "realSpend",
        "spend",
        "advSpend",
        "target",
        "firstTarget",
        "time",
        "cSpend",
        "reportSpend",
        "kcSpend",
        "userAction",
        "action1",
        "userAction1",
        "action2",
        "userAction2",
        "action3",
        "userAction3",
        "action4",
        "userAction4",
        "action5",
        "userAction5",
    );

}

?>
